### ISSUE TITLE
What accuracy did you get?

### ISSUE THREAD

**Issue by wassname** [bolgebrygg/MalenoV#1]
This is an cool project, it's nice to see how Conv3d works for facies prediction.

Did you record any metrics e.g. f1-score when segmenting the test lines? And have/will you write up results anywhere other than the user guide?

Cheers,
Mike

**Comment by bolgebrygg** [comment]
Hi Mike
we did not record scores as the project was of such short duration. 
We only had a week to test out the reuslts. 
We will not write up results any more than the training manual. 
There will be a new version of MalenoV  .. MalenoVxd that will be able to handle n number of input cubes for the classification. (Hopefully in 2 weeks times) We will test this tool and the accuracies in detail
Visually it looked like more than 90% accuracy of prediction versus input but there may be some overfitting.
Would be great if you can  use it and publish on your workd

cheers peter

**Comment by wassname** [comment]
Yeah 90% sounds about right. 

If you do run metrics you might want to think about flattening each result and passing them into scikit learns confusion matrix and classification report, I always find that the easiest way to get metrics on a segmentation problem. Plus you can make some pretty graphs. But you probably have your own ideas.

MalenoVxd sounds cool, it will be even nicer to see how it generalizes across surveys. Right now, working within one survey, it's comparable to the geostatistics tools in Petrel that extrapolate rock values/facies across a volume. Which is very cool

If I run it and get metrics I'll let you know, I'm not planning to at the moment though.
